### ISSUE TITLE
Проблема с нарезкой размеров

### ISSUE THREAD

**Issue by tostr** [Mauhem/selectel-storage-upload#4]
Заметил странную штуку, если выбрать опцию "Сохранять только в Selectel Storage", сохраняется только оригинал, а вот нарезки вообще отсутствуют, и в медиа библиотеке картинка отображается как простой файл. Если галочку убрать, то всё сохраняется нормально, но остаётся копия файлов на сервере-оригинале.  
![screen shot 2015-01-12 at 2 02 15 pm](https://cloud.githubusercontent.com/assets/2136460/5702496/ab9b5e44-9a63-11e4-9ea7-4319c538555b.png)
> Слева картинка загружена только в облако, справа - с копией на сервере-оригинале.

**Comment by Mauhem** [comment]
Исправил в версии 1.3.0. Пожалуйста, обновитесь из репозитория через встроенную функцию обновления.
P.S. Извиняюсь за задержку.
